Update dockerfile

diff --git a/app/Dockerfile b/app/Dockerfile
--- a/app/Dockerfile
+++ b/app/Dockerfile
@@ -3,6 +3,10 @@
 # This Dockerfile uses the service folder as context.
 
 
+# ----------------
+# Global
+# ----------------
+
 # --
 # Global build arguments
 
@@ -12,140 +16,156 @@ ARG UID=1001
 # --
 # Upstream images
 
-FROM node:22-slim AS node_upstream
-FROM bitnami/nginx:1.29 AS nginx_upstream
+FROM alpine:3.22 AS alpine_upstream
+FROM node:24-slim AS node_upstream
+FROM nginx:1.29-alpine AS nginx_upstream
 
 
 # --
-# Base image
+# Alpine base stage
 
-FROM node_upstream AS app_base
+FROM alpine_upstream AS alpine_base
 
 # Set app directory
 WORKDIR /app
 
-# Use temporary directory as home
+
+# --
+# Node base image
+
+FROM node_upstream AS node_base
+
+# Set app directory
+WORKDIR /app
+
+# Set home directory for cache
 ENV HOME=/tmp
 
 
 # --
-# Build base image
+# Build base stage
 
-FROM app_base AS app_build_base
+FROM node_base AS node_build_base
 
 # Install pnpm
-RUN --mount=type=cache,target=~/.npm \
-	npm install -g pnpm
+RUN --mount=type=cache,id=npm,target=/root/.npm \
+	npm install -g pnpm@11
 
+
+# ----------------
+# Dependencies
+# ----------------
 
 # --
-# Build dev image
+# Deps base stage
 
-FROM app_build_base AS app_build_dev
+FROM node_build_base AS deps_base
 
-# Copy app build configuration
-COPY --link ./app/package.json ./app/pnpm-lock.yaml ./
+# Create Astro runtime directory
+RUN mkdir -p ./.astro
 
-# Install app development dependencies
+# Copy build configuration
+COPY --link ./package.json ./pnpm-lock.yaml ./pnpm-workspace.yaml ./
+
+# --
+# Deps dev stage
+
+FROM deps_base AS deps_dev
+
+# Install dev dependencies
 RUN --mount=type=cache,id=pnpm,target=/pnpm/store \
 	pnpm install --frozen-lockfile
 
 
 # --
+# Deps prod stage
+
+FROM deps_base AS deps_prod
+
+# Install prod dependencies
+RUN --mount=type=cache,id=pnpm,target=/pnpm/store \
+	pnpm install --prod --frozen-lockfile
+
+
+# ----------------
+# CLI
+# ----------------
+
+# --
 # CLI image
 
-FROM app_build_base AS app_cli
+FROM node_build_base AS app_cli
 
+# Build arguments
 ARG UID
 
 # Install sudo
 # (hadolint: Ignore non-pinned apt package version)
 # hadolint ignore=DL3008
-RUN --mount=type=cache,sharing=locked,target=/var/cache/apt \
-	--mount=type=cache,sharing=locked,target=/var/lib/apt \
+RUN --mount=type=cache,sharing=locked,id=apt-cache,target=/var/cache/apt \
+	--mount=type=cache,sharing=locked,id=apt-lib,target=/var/lib/apt \
 	apt-get update && \
 	apt-get install -y --no-install-recommends sudo && \
 	echo '%sudo ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers
 
 # Create user 'user' in group 'root' & 'sudo'
-RUN USERNAME="$(getent passwd "${UID}" | cut -d: -f1)"; \
+# (hadolint: Ignore unchecked pipe failures)
+# hadolint ignore=DL4006
+RUN USERNAME="$(getent passwd "${UID}" 2>/dev/null | cut -d: -f1 || true)"; \
 	if [ -z "${USERNAME}" ]; then \
 		useradd -lm -u "${UID}" -U -G 0,sudo user; \
 	else \
 		usermod -a -G 0,sudo "${USERNAME}"; \
 	fi
 
-# Run as non-root user
-USER ${UID}:0
+# Run as created non-root user
+USER ${UID}
 
 # Mount source code
 VOLUME /app
 
-# Run CLI command
+# Copy scripts
 COPY --link --chmod=755 ./docker/cli-entrypoint.sh /usr/local/bin/app-cli-entrypoint
-ENTRYPOINT [ "app-cli-entrypoint" ]
-CMD [ "--help" ]
 
+ENTRYPOINT [ "app-cli-entrypoint" ]
+CMD []
+
+
+# ----------------
+# Source code
+# ----------------
 
 # --
-# Dev image
+# Source dev stage
 
-FROM app_base AS app_dev
+FROM alpine_base AS source_dev
 
-ARG UID
-
-# Set runtime environment
-ENV APP_ENV=dev
-ENV NODE_ENV=development
-
-# Copy app development dependencies
-COPY --link --from=app_build_dev --chown="${UID}:0" /app/node_modules ./node_modules
+# Copy dev dependencies
+COPY --from=deps_dev --link /app/.astro/ ./.astro/
+COPY --from=deps_dev --link /app/node_modules/ ./node_modules/
 
 # Copy source code
-COPY --link --chown="${UID}:0" ./app .
-RUN mkdir -p ./.astro && chown -R "${UID}:0" ./.astro
-
-# Create user 'user' in group 'root'
-RUN USERNAME="$(getent passwd "${UID}" | cut -d: -f1)"; \
-	if [ -z "${USERNAME}" ]; then \
-		useradd -lm -u "${UID}" -U -G 0 user; \
-	else \
-		usermod -a -G 0 "${USERNAME}"; \
-	fi
-
-# Run as non-root user
-USER ${UID}:0
-
-# Set exposed port
-ARG PORT=8080
-ENV PORT=${PORT}
-EXPOSE ${PORT}
-
-# Start development server
-CMD [ "sh", "-c", "npm run dev -- --host --port \"${PORT}\"" ]
+COPY --link ./ ./
 
 
 # --
-# Prod build image
+# Source prod build stage
 
-FROM app_base AS app_prod_build
-
-ARG UID
+FROM node_build_base AS source_prod_build
 
 # Set runtime environment
-ENV APP_ENV=prod
+ARG APP_ENV=prod
+ENV APP_ENV=${APP_ENV}
 ENV NODE_ENV=production
 
-# Install git, used to fetch history during build
+# Install & configure git, used to fetch history during build
 RUN --mount=type=cache,target=/var/cache/apt \
 	apt-get update && \
-	apt-get install -y git
+	apt-get install -y git && \
+	git config --global --add safe.directory /app
 
-# Copy app development dependencies
-COPY --link --from=app_build_dev --chown="${UID}:0" /app/node_modules ./node_modules
-
-# Copy source code
-COPY --link --chown="${UID}:0" ./app .
+# Copy dev dependencies & source code
+COPY --from=source_dev --link /app/ ./
 
 # Set app environment variables
 # : Deployment configuration
@@ -165,27 +185,180 @@ ENV ASTRO_ASSETS_PREFIX=${ASTRO_ASSETS_PREFIX}
 # : Application configuration
 # Add env vars for your application here.
 
-# Build application
+# Build application in dist/ directory
 ARG BUILD_CHECK='true'
 RUN if [ "${BUILD_CHECK}" = 'true' ]; then \
-		npm run build; \
+		pnpm run build; \
 	else \
-		npm run build-only; \
+		pnpm run build-only; \
 	fi
 
+
+# --
+# Source prod stage
+
+FROM alpine_base AS source_prod
+
+# Copy prod dependencies
+COPY --from=deps_prod --link /app/node_modules/ ./node_modules/
+
+# Copy built prod application files
+COPY --from=source_prod_build --link /app/dist/ ./dist/
+
+
+# ----------------
+# Lint
+# ----------------
+
+# --
+# Lint image
+
+FROM node_build_base AS app_lint
+
+# Build arguments
+ARG UID
+
+# Set runtime environment
+ENV APP_ENV=test
+
+# Run as non-root user
+USER ${UID}:0
+
+CMD [ "sh", "-c", "exit 0" ]
+
+
+# ----------------
+# Test
+# ----------------
+
+# --
+# Test base stage
+
+FROM node_build_base AS test_base
+
+# Build arguments
+ARG UID
+
+# Set runtime environment
+ENV APP_ENV=test
+ENV NODE_ENV=development
+
+
+# --
+# Test unit image
+
+FROM test_base AS test_unit
+
+# Build arguments
+ARG UID
+
+# Copy dev dependencies & source code
+RUN chown "${UID}:0" .
+COPY --from=source_dev --link --chown="${UID}:0" /app/ ./
+
+# Run as non-root user
+USER ${UID}:0
+
+CMD [ "sh", "-c", "pnpm run test:vitest" ]
+
+
+# --
+# Test E2E image
+
+FROM test_base AS test_e2e
+
+# Build arguments
+ARG UID
+
+# Copy dev dependencies
+COPY --from=source_dev --link --chown="${UID}:0" /app/.astro/ ./.astro/
+COPY --from=source_dev --link --chown="${UID}:0" /app/node_modules/ ./node_modules/
+
+# Install Playwright dependencies
+ENV PLAYWRIGHT_BROWSERS_PATH=/etc/playwright/browsers
+COPY --from=deps_dev --link --chown="${UID}:0" /app/package.json /app/pnpm-lock.yaml /app/pnpm-workspace.yaml ./
+RUN pnpm exec playwright install --with-deps
+
+# Copy dev source code
+RUN chown "${UID}:0" .
+COPY --from=source_dev --link --chown="${UID}:0" /app/ ./
+
+# Build application
+RUN pnpm run build-only
+
+# Run as non-root user
+USER ${UID}:0
+
+CMD [ "sh", "-c", "pnpm run test:playwright --output /tmp/playwright/test-results" ]
+
+
+# ----------------
+# Dev
+# ----------------
+
+# --
+# Dev image
+
+FROM node_build_base AS app_dev
+
+# Build arguments
+ARG UID
+
+# Set runtime environment
+ENV APP_ENV=dev
+ENV NODE_ENV=development
+
+# Copy dev dependencies & source code
+RUN chown "${UID}:0" .
+COPY --from=source_dev --link --chown="${UID}:0" /app/ ./
+
+# Create user 'user' in group 'root'
+# (hadolint: Ignore unchecked pipe failures)
+# hadolint ignore=DL4006
+RUN USERNAME="$(getent passwd "${UID}" 2>/dev/null | cut -d: -f1 || true)"; \
+	if [ -z "${USERNAME}" ]; then \
+		useradd -lm -u "${UID}" -U -G 0 user; \
+	else \
+		usermod -a -G 0 "${USERNAME}"; \
+	fi
+
+# Run as created non-root user
+USER ${UID}
+
+# Set exposed port
+ARG PORT=8080
+ENV PORT=${PORT}
+EXPOSE ${PORT}
+
+CMD [ "sh", "-c", "pnpm run dev --host --port \"${PORT}\"" ]
+
+
+# ----------------
+# Prod
+# ----------------
 
 # --
 # Prod image
 
 FROM nginx_upstream AS app_prod
 
+# Build arguments
+ARG UID
+
 # Set runtime environment
 ENV APP_ENV=prod
 
-# Copy app production built files
-COPY --from=app_prod_build --link /app/dist .
+# Copy nginx configuration
+COPY --link ./nginx/default.conf.template /etc/nginx/templates/
+
+# Copy built prod application files
+COPY --from=source_prod --link --chown="${UID}:0" /app/dist/ /usr/share/nginx/html/
+
+# Set environment variables
+ARG NGINX_HOST='localhost'
+ENV NGINX_HOST=${NGINX_HOST}
 
 # Set exposed port
-ARG PORT=8080
-ENV NGINX_HTTP_PORT_NUMBER=${PORT}
+ARG PORT='8080'
+ENV NGINX_PORT=${PORT}
 EXPOSE ${PORT}
